services:
  - type: web
    name: app-fullstack
    runtime: docker
    repo: https://github.com/VOTRE_USERNAME/VOTRE_REPO.git # Remplacez par votre repo GitHub
    branch: main # ou master selon votre branche principale
    dockerfilePath: ./Dockerfile
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Variables d'environnement pour votre base de données
      # Ajoutez vos variables selon vos besoins :
      # - key: DB_HOST
      #   value: your-db-host
      # - key: DB_PORT
      #   value: 5432
      # - key: DB_USERNAME
      #   value: your-db-username
      # - key: DB_PASSWORD
      #   value: your-db-password  
      # - key: DB_NAME
      #   value: your-db-name
      # - key: JWT_SECRET
      #   value: your-jwt-secret
    healthCheckPath: /
    region: oregon # ou une autre région selon vos préférences
    plan: free # starter, standard, pro selon vos besoins
    autoDeploy: true
    buildCommand: docker build -t app .
    startCommand: docker run -p $PORT:$PORT app
