services:
  - type: web
    name: marketplace-fullstack
    runtime: docker
    repo: https://github.com/VOTRE_USERNAME/VOTRE_REPO.git # Remplacez par votre repo GitHub
    branch: main # ou master selon votre branche principale
    dockerfilePath: ./Dockerfile
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://marketplace_db_qgvb_user:WToQLLnZ6wgBevVGnEvNkBBF7dRdjHDf@dpg-d15o6t8dl3ps7380bppg-a.frankfurt-postgres.render.com/marketplace_db_qgvb
      - key: JWT_SECRET
        value: votre-secret-jwt-tres-securise-pour-production-changez-moi
      - key: STRIPE_SECRET_KEY
        value: sk_test_51Qm0WHCA9knPbVsZV3Jk2uT9CwO9XxggFei9BTMt5nxi7HilISXmTsMFtGnQibrVH0XaLnsyI1uaXuW1Z9zASOqI00OmIaqEny
      - key: FRONTEND_URL
        value: https://test-hjc1.onrender.com
      - key: CORS_ORIGIN
        value: https://test-hjc1.onrender.com
    healthCheckPath: /api
    region: frankfurt # Pour correspondre à votre base de données
    plan: free
    autoDeploy: true
